import Cocoa
import CoreGraphics

/// Intercepts keyboard events for Cmd+X, Cmd+C, Cmd+V, and Escape when Finder is active.
public final class EventMonitor: @unchecked Sendable {
    public static let shared = EventMonitor()
    
    // Magic marker value to identify synthetic events generated by CutX ("CUTX" in hex)
    private let cutxEventMarker: Int64 = 0x43555458
    
    private var eventTap: CFMachPort?
    private var runLoopSource: CFRunLoopSource?
    private let contextInspector = ContextInspector.shared
    
    private init() {}
    
    /// Starts the global event tap listener.
    public func start() {
        guard eventTap == nil else { return }
        
        let eventMask = (1 << CGEventType.keyDown.rawValue)
        
        guard let tap = CGEvent.tapCreate(
            tap: .cgAnnotatedSessionEventTap,
            place: .headInsertEventTap,
            options: .defaultTap,
            eventsOfInterest: CGEventMask(eventMask),
            callback: { proxy, type, event, refcon in
                guard let refcon = refcon else {
                    return Unmanaged.passRetained(event)
                }
                let monitor = Unmanaged<EventMonitor>.fromOpaque(refcon).takeUnretainedValue()
                return monitor.handleEvent(proxy: proxy, type: type, event: event)
            },
            userInfo: Unmanaged.passUnretained(self).toOpaque()
        ) else {
            return
        }
        
        self.eventTap = tap
        let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
        self.runLoopSource = source
        CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
        CGEvent.tapEnable(tap: tap, enable: true)
    }
    
    /// Stops the event tap listener.
    public func stop() {
        if let tap = eventTap {
            CGEvent.tapEnable(tap: tap, enable: false)
            if let source = runLoopSource {
                CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes)
            }
            self.eventTap = nil
            self.runLoopSource = nil
        }
    }
    
    /// Synthesizes a key combination using CGEvent with CutX marker.
    private func synthesizeKey(keyCode: CGKeyCode, flags: CGEventFlags) {
        let source = CGEventSource(stateID: .combinedSessionState)
        
        if let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true) {
            keyDown.flags = flags
            keyDown.setIntegerValueField(.eventSourceUserData, value: cutxEventMarker)
            keyDown.post(tap: .cghidEventTap)
        }
        
        if let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false) {
            keyUp.flags = flags
            keyUp.setIntegerValueField(.eventSourceUserData, value: cutxEventMarker)
            keyUp.post(tap: .cghidEventTap)
        }
    }
    
    /// Handles intercepted keyboard events.
    private func handleEvent(proxy: CGEventTapProxy, type: CGEventType, event: CGEvent) -> Unmanaged<CGEvent>? {
        // Automatically re-enable tap if macOS disabled it due to timeout
        if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
            if let tap = eventTap {
                CGEvent.tapEnable(tap: tap, enable: true)
            }
            return Unmanaged.passRetained(event)
        }
        
        guard type == .keyDown else {
            return Unmanaged.passRetained(event)
        }
        
        // If this event was synthesized by CutX, pass it through directly
        if event.getIntegerValueField(.eventSourceUserData) == cutxEventMarker {
            return Unmanaged.passRetained(event)
        }
        
        // 1. Filter: Only handle when Finder is frontmost
        guard contextInspector.isFinderFrontmost() else {
            return Unmanaged.passRetained(event)
        }
        
        let keycode = event.getIntegerValueField(.keyboardEventKeycode)
        let flags = event.flags
        let isCmdDown = flags.contains(.maskCommand)
        let isOptionDown = flags.contains(.maskAlternate)
        let isControlDown = flags.contains(.maskControl)
        let isShiftDown = flags.contains(.maskShift)
        
        // Pure Command key modifier (without Option, Control, Shift)
        let isPureCmd = isCmdDown && !isOptionDown && !isControlDown && !isShiftDown
        
        // Keycodes:
        // Keycode 7 = 'X'
        // Keycode 8 = 'C'
        // Keycode 9 = 'V'
        // Keycode 53 = 'Escape'
        
        // 2. Handle Escape: Clear cut state
        if keycode == 53 && !isCmdDown {
            Task { @MainActor in
                CutEngine.shared.clear()
            }
            return Unmanaged.passRetained(event)
        }
        
        guard isPureCmd else {
            return Unmanaged.passRetained(event)
        }
        
        // 3. Bypass if user is actively typing in a text field (e.g. renaming file)
        if contextInspector.isTextInputFocused() {
            return Unmanaged.passRetained(event)
        }
        
        // 4. Handle Cmd + C (Normal Copy): Deactivate cut mode so subsequent Cmd+V copies instead of moves
        if keycode == 8 {
            Task { @MainActor in
                CutEngine.shared.deactivateCut(playFeedback: false)
            }
            return Unmanaged.passRetained(event)
        }
        
        // 5. Handle Cmd + X (Cut File/Folder)
        if keycode == 7 {
            // Synthesize Cmd + C to place selected Finder items into clipboard
            synthesizeKey(keyCode: 8, flags: .maskCommand)
            
            Task { @MainActor in
                CutEngine.shared.activateCut()
            }
            
            // Consume the Cmd + X event so Finder does not produce an error beep
            return nil
        }
        
        // 6. Handle Cmd + V (Paste -> Move if Cut is active, Copy if not)
        if keycode == 9 {
            var isCut = false
            
            if Thread.isMainThread {
                MainActor.assumeIsolated {
                    isCut = CutEngine.shared.isCutActive
                }
            } else {
                DispatchQueue.main.sync {
                    MainActor.assumeIsolated {
                        isCut = CutEngine.shared.isCutActive
                    }
                }
            }
            
            if isCut {
                // Synthesize Option + Cmd + V (Finder's native "Move Item Here" shortcut!)
                synthesizeKey(keyCode: 9, flags: [.maskCommand, .maskAlternate])
                
                Task { @MainActor in
                    CutEngine.shared.deactivateCut(playFeedback: true)
                }
                
                // Consume the original Cmd + V event so Finder doesn't perform standard duplicate copy
                return nil
            }
        }
        
        return Unmanaged.passRetained(event)
    }
}
