name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Swift & Xcode version
        run: |
          swift --version
          xcodebuild -version

      - name: Build CutX (Debug)
        run: swift build -v

      - name: Build CutX (Release)
        run: swift build -c release -v
